{"archive_info": {"hash": "sha256=232c37c63e4f682982c8b6459f33a8981039e5fb8756b2074364e5055c498c9e"}, "url": "https://files.pythonhosted.org/packages/61/97/17ed81b7a8d24d8f69b62c0db37abbd8c0042d4b3fc429c73dab986e7483/exceptiongroup-1.1.1-py3-none-any.whl"}